# Generated by Django 2.2.3 on 2019-07-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPositionDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('teamPositionDictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.TeamPositionDictionary')),
            ],
        ),
        migrations.CreateModel(
            name='MapValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1)),
                ('value', models.IntegerField(default=501)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.Map')),
            ],
        ),
    ]
