# Generated by Django 2.2.3 on 2019-07-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='map',
            old_name='key',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='teampositiondictionary',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
