# Generated by Django 2.2.3 on 2019-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_auto_20190730_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=100000)),
                ('team_position', models.CharField(max_length=10000)),
                ('team_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MapKey',
        ),
        migrations.RemoveField(
            model_name='mapvalues',
            name='map',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='teamPositionDictionary',
        ),
        migrations.DeleteModel(
            name='TeamScore',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='MapValues',
        ),
        migrations.DeleteModel(
            name='TeamPosition',
        ),
        migrations.DeleteModel(
            name='TeamPositionDictionary',
        ),
    ]
